### ISSUE TITLE
CDN Caching

### ISSUE THREAD

**Issue by davidh61** [CreunaAB/EPiFocalPoint#15]
When updating the focal point of images, the CDN for our Episerver site does not invalidate the cache for the images so therefore doesn't update until we manually invalidate the cache ourselves

**Comment by defsteph** [comment]
That, I believe, hasn't got anything to do with the focal point, but rather how you have configured caching of static files. Your CDN can only deal with what it is told and, in your case, Episerver is telling it to cache it depending on your configuration.

I have run into similar issues, and have chosen to solve it with another plugin, https://github.com/defsteph/UniqueUrlFolderPresets.

As this isn't related to the setting of the focal point, I will close this.

**Comment by davidh61** [comment]
Yes that's fair enough Stephen, that plugin looks very helpful though thank you! Will let you know how I get on with it
