### ISSUE TITLE
No Reference to ImageResizer.Plugins.EPiFocalPoint is added

### ISSUE THREAD

**Issue by perhassle** [CreunaAB/EPiFocalPoint#3]

**Comment by defsteph** [comment]
This is due to the fact that we target net461, and you have net46 as targetFramework in you project.

_(note: we had that discussion separately)_

**Comment by defsteph** [comment]
Fixed in release [1.1.1](https://github.com/CreunaAB/EPiFocalPoint/releases/tag/1.1.1)
