### ISSUE TITLE
Alloy example

### ISSUE THREAD

**Issue by klavsi** [CreunaAB/EPiFocalPoint#5]
Hi!

Could you, please, commit example based on Alloy?

Thanks!

**Comment by valdisiljuconoks** [comment]
We had issues getting plugin to work and would love to see sample project with plugin in action. Thanks!

**Comment by defsteph** [comment]
What are the issues you've been having?

In regards to a sample, there's really not that much to it.
1. Install Alloy Sample.
2. Install EPiFocalPoint (it will install the BlobReader and ImageResizer)
3. Ensure config is correct for ImageResizer, especially the InterceptModule.
4. Implement the interface IFocalPointData on the ImageData Media Type.
5. Add the backingtype attribute to the FocalPoint property.

Test by editing an image, go to AllPropertiesView and set a focal point. Open up the image and add parameters that crops the image.

Please note that unless the aspect ratio of the image are changed, the focal point doesn't matter. The purpose of the plugin is to ensure that the focal point is included in crops, not alter how images are cropped in any other way.

**Comment by valdisiljuconoks** [comment]
What's code snippet for rendering the image? `Html.PropertyFor()`?

**Comment by defsteph** [comment]
There's no Html Helper in the package, you can use your helpers from the BlobReader package.

**Comment by valdisiljuconoks** [comment]
Ok. But how you output the image in your sample? I suspect that BlobReader might shallow `crop`. I do see only `<img src="...image1.jpg?w=150">`. I see in code that you modify rewrite defaults. Not sure exactly how that affects IR pipeline thou.

**Comment by defsteph** [comment]
What do mean by shallow crop?

Also, only passing a width parameter will not change the aspect ratio of your output image, so the focal point won't affect the end result.
